services:
  rstudio:
    container_name: r440container
    image: r440image:latest
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=password
      - DISABLE_AUTH=true
      - RENV_PATHS_CACHE=/home/rstudio/.local/share/renv/cache
    volumes:
      - ./project:/home/rstudio/project
      - ./.devcontainer:/home/rstudio/.devcontainer
      - ${RENV_PATHS_CACHE_HOST}:/home/rstudio/.local/share/renv/cache